### ISSUE TITLE
Compilare il primo report

### ISSUE THREAD

**Issue by 20017578** [20017578/MasterSoftwareLibero#6]
Serve completare il [primo report](../blob/master/Report_I.md).

Punti che in particolare necessitano di attenzione:
- [ ] Titolo (ho messo provvisoriamente **Open Data** ma va cambiato)
- [ ] Aspetti organizzativi
  - [x] introduzione
  - [ ] dettaglio
- [ ] Aspetti tecnici (da strutturare!)
  - [x] Dati trasparenza
  - [x] Dati scuole già pubblicati
  - [x] Dati edifici scolastici Piemonte
- [ ] Aspetti giuridici (generalmente strutturato: problemi, modelli, soluzioni; forse da suddividere per aspetti?)
  - [X] licenze
  - [ ] privacy
- [ ] Gestione del cambiamento (se vogliamo approfondirla)
- [X] Appendice A (mirata ai formati)

Sarebbe bene che ci mettessimo mano un po' tutti: @guido612 , @claudiaconforti , @annaale , @gverda , @20017578 .

**Comment by 20017578** [comment]
Intanto mi rispondo da solo dicendo che scriverò volentieri due parole sulle licenze (per dati aperti)

**Comment by 20017578** [comment]
Ho scritto un capitoletto sulle licenze: a4a5fe60f03be128c642bd9a3a99d540605c100d

**Comment by 20017578** [comment]
Impostata struttura minimale per il lavoro sui dati delle scuole: b83c96d598ffd6adcb1e15d957bf89d910d3d011

**Comment by 20017578** [comment]
Ora ci dovremo dedicare al secondo...

**Comment by guido612** [comment]
Buongiorno a tutti,
so che siete presi dal fantasma della Songini .. in ogni caso ho provato a
definire una possibile mail da inviare in Finlandia in merito ad ottenere
alcune informazioni sul progetto Hri di cui l'articolo che vi inoltrai
giorni fa. Ovviamente lo trovate su github:
https://github.com/20017578/MasterSoftwareLibero/blob/master/AmbitoOrganizzativo/mail_hri.md

Se avete tempo dategli un'occhiata ...

E ricordatevi che "L'Ente Pubblico fornisce servizi intangibili" Songini,
2016

Buona serata

guido

2016-04-12 8:43 GMT+02:00 20017578 notifications@github.com:
